#!/usr/bin/env node
const http = require('http');
const { spawn } = require('child_process');

const args = process.argv.slice(2);
let port = null;
let syncMachines = [];

for (let i = 0; i < args.length; i++) {
    if (args[i] === '-p' && i + 1 < args.length) {
        port = parseInt(args[++i], 10);
    } else {
        syncMachines.push(args[i]);
    }
}

if (port === null || syncMachines.length === 0) {
    console.error('Usage: ./script_name -p <port> <sync_machine_ip> [...]');
    process.exit(1);
}

const handleRequest = (req, res) => {
    let body = '';
    req.on('data', (chunk) => {
        body += chunk.toString();
    });

    req.on('end', () => {
        const wlCopy = spawn('wl-copy');

        wlCopy.stdin.write(body);
        wlCopy.stdin.end();

        res.statusCode = 200;
        res.end('Copied To Clipboard\n');
    });
};


const server = http.createServer(handleRequest);
server.listen(port, () => {
    console.log(`Server listening on port ${port}`);
});

const handleWlPaste = () => {
    syncMachines.forEach((ip) => {
        const url = `http://${ip}:${port}`;
        const command = `wl-paste --watch sh -c "curl -X POST ${url} -d '$(wl-paste)'"`;

        spawn('sh', ['-c', command], {
            stdio: 'inherit',
        });
    });
};

handleWlPaste();
